package types

type COLUMN_TYPE int32

const (
	INVALID_TYPE COLUMN_TYPE = iota
	VAR_CHAR_TYPE
	INT_TYPE
	LONG_INT_TYPE
	FLOAT_TYPE
	BOOL_TYPE
)

const (
	COLUMN_TYPE_VAR_CHAR = "VARCHAR"
	COLUMN_TYPE_INT      = "INT"
	COLUMN_TYPE_LONGINT  = "BIGINT"
	COLUMN_TYPE_FLOAT    = "FLOAT"
	COLUMN_TYPE_BOOL     = "BOOL"
	COLUMN_TYPE_INVALID  = "INVALID"
)

const (
	COLUMN_NAME_OFFSET = 128
	COLUMN_TYPE_OFFSET = 4
	COLUMN_SIZE_OFFSET = 4
)

const (
	BOOL_SIZE     = 4
	INT_SIZE      = 4
	FLOAT_SIZE    = 8
	LONG_INT_SIZE = 8
	VAR_CHAR_SIZE = 52
)
